#!/usr/bin/env node
/**
 * Vercel Environment Variables Setup Script
 * 
 * This script helps you set up environment variables for Vercel deployment.
 * It creates a .env file locally and optionally pushes to Vercel.
 * 
 * Usage:
 *   node scripts/vercel-setup.js
 *   node scripts/vercel-setup.js --push
 * 
 * Prerequisites:
 *   - Vercel CLI installed: npm i -g vercel
 *   - Logged in: vercel login
 */

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ENV_FILE = path.join(__dirname, '..', '.env');
const REQUIRED_VARS = [
  { key: 'VITE_FIREBASE_API_KEY', required: true, generate: () => '' },
  { key: 'VITE_FIREBASE_AUTH_DOMAIN', required: true, generate: () => 'dwd-it2-92aa4.firebaseapp.com' },
  { key: 'VITE_FIREBASE_PROJECT_ID', required: true, generate: () => 'dwd-it2-92aa4' },
  { key: 'VITE_FIREBASE_STORAGE_BUCKET', required: true, generate: () => 'dwd-it2-92aa4.firebasestorage.app' },
  { key: 'VITE_FIREBASE_MESSAGING_SENDER_ID', required: true, generate: () => '939613662564' },
  { key: 'VITE_FIREBASE_APP_ID', required: true, generate: () => '1:939613662564:web:4b6142cd66b17f28d3de71' },
  { key: 'VITE_FIREBASE_MEASUREMENT_ID', required: false, generate: () => 'G-YSH146MSCB' },
  { key: 'VITE_SUPABASE_URL', required: true, generate: () => 'https://suziirfasrahhaqffymz.supabase.co' },
  { key: 'VITE_SUPABASE_ANON_KEY', required: true, generate: () => '' },
  { key: 'SUPABASE_SERVICE_ROLE_KEY', required: true, generate: () => '' },
  { key: 'BATU_SSO_SECRET', required: true, generate: () => crypto.randomBytes(32).toString('hex') },
  { key: 'BATU_ALLOWED_ORIGIN', required: true, generate: () => 'https://dwd-edu.vercel.app' },
  { key: 'GEMINI_API_KEY', required: false, generate: () => '' },
];

function generateRandomSecret() {
  return crypto.randomBytes(32).toString('hex');
}

function readExistingEnv() {
  try {
    const content = fs.readFileSync(ENV_FILE, 'utf8');
    const env = {};
    content.split('\n').forEach(line => {
      const match = line.match(/^([^=]+)=(.*)$/);
      if (match) env[match[1].trim()] = match[2].trim();
    });
    return env;
  } catch {
    return {};
  }
}

function writeEnvFile(vars) {
  const lines = [
    '# ⚠️ CRITICAL: This file should NEVER be committed to Git!',
    '# Auto-generated by scripts/vercel-setup.js',
    '',
  ];

  for (const [key, value] of Object.entries(vars)) {
    if (value) {
      lines.push(`${key}=${value}`);
    }
  }

  fs.writeFileSync(ENV_FILE, lines.join('\n') + '\n');
  console.log('✅ Created .env file');
}

function promptForValue(key, currentValue, required) {
  if (currentValue) {
    const keep = prompt(`${key} already exists. Keep current value? (y/n): `);
    if (keep && keep.toLowerCase() === 'y') {
      return currentValue;
    }
  }

  if (required) {
    const value = prompt(`Enter ${key}: `);
    if (!value) {
      console.error(`❌ ${key} is required!`);
      process.exit(1);
    }
    return value;
  }

  const value = prompt(`Enter ${key} (optional, press Enter to skip): `);
  return value || '';
}

function prompt(question) {
  const readline = require('readline').createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise(resolve => {
    readline.question(question, answer => {
      readline.close();
      resolve(answer);
    });
  });
}

async function main() {
  const shouldPush = process.argv.includes('--push');
  const existingEnv = readExistingEnv();
  
  console.log('\n🚀 Vercel Environment Variables Setup\n');
  console.log('This script will help you configure your .env file.\n');

  const newVars = {};
  
  for (const varDef of REQUIRED_VARS) {
    const currentValue = existingEnv[varDef.key];
    let value;

    if (varDef.generate && !currentValue) {
      if (varDef.key === 'BATU_SSO_SECRET') {
        value = generateRandomSecret();
        console.log(`🔑 Generated ${varDef.key}: ${value}`);
      } else if (varDef.key === 'GEMINI_API_KEY') {
        value = promptForValue(varDef.key, currentValue, varDef.required);
      } else {
        value = varDef.generate();
        console.log(`✓ ${varDef.key}: ${value}`);
      }
    } else {
      value = promptForValue(varDef.key, currentValue, varDef.required);
    }

    newVars[varDef.key] = value;
  }

  writeEnvFile(newVars);

  if (shouldPush) {
    console.log('\n📤 Pushing to Vercel...');
    try {
      execSync('vercel env add VITE_FIREBASE_API_KEY production', { stdio: 'inherit' });
      execSync('vercel env add VITE_FIREBASE_AUTH_DOMAIN production', { stdio: 'inherit' });
      execSync('vercel env add VITE_FIREBASE_PROJECT_ID production', { stdio: 'inherit' });
      execSync('vercel env add VITE_FIREBASE_STORAGE_BUCKET production', { stdio: 'inherit' });
      execSync('vercel env add VITE_FIREBASE_MESSAGING_SENDER_ID production', { stdio: 'inherit' });
      execSync('vercel env add VITE_FIREBASE_APP_ID production', { stdio: 'inherit' });
      execSync('vercel env add VITE_FIREBASE_MEASUREMENT_ID production', { stdio: 'inherit' });
      execSync('vercel env add VITE_SUPABASE_URL production', { stdio: 'inherit' });
      execSync('vercel env add VITE_SUPABASE_ANON_KEY production', { stdio: 'inherit' });
      execSync('vercel env add SUPABASE_SERVICE_ROLE_KEY production', { stdio: 'inherit' });
      execSync('vercel env add BATU_SSO_SECRET production', { stdio: 'inherit' });
      execSync('vercel env add BATU_ALLOWED_ORIGIN production', { stdio: 'inherit' });
      console.log('✅ All environment variables pushed to Vercel');
    } catch (error) {
      console.error('❌ Failed to push to Vercel:', error.message);
      console.log('\n💡 You can manually add them in Vercel Dashboard → Settings → Environment Variables');
    }
  } else {
    console.log('\n💡 Next steps:');
    console.log('1. Review the .env file');
    console.log('2. Add these variables to Vercel Dashboard → Settings → Environment Variables');
    console.log('3. Run "vercel --prod" to deploy');
    console.log('\nOr run "node scripts/vercel-setup.js --push" to push automatically.\n');
  }
}

main().catch(console.error);
